# Generated by Django 4.0.3 on 2022-03-27 01:43

import audios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('audio_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='asmaul-husna', max_length=250)),
                ('image', models.ImageField(default=None, upload_to=audios.models.upload_to, verbose_name='Image')),
                ('audio', models.FileField(default=None, upload_to=audios.models.upload_to)),
            ],
        ),
    ]
