# Generated by Django 4.0.3 on 2022-03-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='audio',
        ),
    ]
