# Generated by Django 4.0.3 on 2022-03-27 08:00

import audios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_remove_audios_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='audio',
            field=models.FileField(default=None, upload_to=audios.models.upload_to),
        ),
    ]
